version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
       POSTGRES_USER: ${DOCKER_USER}
       POSTGRES_PASSWORD: ${DOCKER_PASS}
       POSTGRES_DB: ${DOCKER_DB}
    ports:
      - '5435:5432'
    # volumes:
    #   - db:/var/lib/postgresql/data
  app:
     restart: on-failure
     build: .
     depends_on:
     - db
    
    
volumes:
  db: {}
    

